import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — PropertySignalHQ',
  description: 'Terms of Service for PropertySignalHQ.',
}

const SECTIONS: { title: string; body?: string; contact?: true }[] = [
  {
    title: '1. Acceptance of Terms',
    body: 'By using PropertySignalHQ.com, you agree to these terms. If you do not agree, do not use the site.',
  },
  {
    title: '2. No Financial Advice',
    body: 'PropertySignalHQ is for informational purposes only. Our "Deal Scores" and "Property Signals" are generated by algorithms and should not be considered financial, legal, or real estate advice. You are responsible for doing your own due diligence before making any investment.',
  },
  {
    title: '3. Description of Service',
    body: 'PropertySignalHQ provides property signal data and deal analysis tools for informational purposes only. Data is algorithmically generated and not guaranteed to be accurate or current. It is not a substitute for professional real estate advice.',
  },
  {
    title: '4. User Accounts',
    body: 'You are responsible for your account security. One account per user.',
  },
  {
    title: '5. Subscription and Billing',
    body: 'The Pro plan is billed monthly at $39.99/month. Cancel anytime through the customer portal. No refunds for partial months.',
  },
  {
    title: '6. Acceptable Use',
    body: 'Use of this service is permitted for personal and commercial real estate research only. Scraping, reselling, or redistribution of data is prohibited. Automated access without written permission is not allowed.',
  },
  {
    title: '7. Limitation of Liability',
    body: 'PropertySignalHQ and its owners are not liable for any financial losses, bad investments, or data inaccuracies resulting from the use of this tool. Use at your own risk.',
  },
  {
    title: '8. Changes to Terms',
    body: 'We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of the updated terms.',
  },
  {
    title: '9. Contact',
    contact: true,
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-[calc(100vh-4rem)] bg-[#020617] relative overflow-hidden px-4 py-16">

      {/* Glow orbs */}
      <div className="pointer-events-none absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-blue-600/20 blur-[120px]" />
      <div className="pointer-events-none absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-indigo-600/10 blur-[120px]" />

      <div className="relative z-10 mx-auto max-w-3xl">

        {/* Back link */}
        <Link href="/" className="text-xs text-blue-400 hover:underline mb-6 inline-block">
          ← Back to Home
        </Link>

        {/* Page header */}
        <div className="mb-10">
          <h1 className="text-4xl font-bold text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-gray-500">Last Updated: March 17, 2026</p>
        </div>

        {/* Content card */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-8 backdrop-blur-xl shadow-2xl space-y-8">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="text-sm font-semibold text-white mb-2">{s.title}</h2>
              {s.contact ? (
                <p className="text-sm text-gray-400 leading-relaxed">
                  Questions? Email:{' '}
                  <a
                    href="mailto:support@propertysignalhq.com"
                    className="text-blue-400 hover:underline"
                  >
                    support@propertysignalhq.com
                  </a>
                </p>
              ) : (
                <p className="text-sm text-gray-400 leading-relaxed">{s.body}</p>
              )}
            </div>
          ))}
        </div>

        {/* Footer links */}
        <p className="mt-8 text-center text-xs text-gray-600">
          <Link href="/privacy" className="hover:text-gray-400 transition-colors">Privacy Policy</Link>
          {' · '}
          <Link href="/about" className="hover:text-gray-400 transition-colors">About</Link>
          {' · '}
          <Link href="/contact" className="hover:text-gray-400 transition-colors">Contact</Link>
        </p>

      </div>
    </div>
  )
}
